# permissions for end users to edit disconnectedfriendlyapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: disconnectedfriendlyapp-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: simple-disconnected-operator
    app.kubernetes.io/part-of: simple-disconnected-operator
    app.kubernetes.io/managed-by: kustomize
  name: disconnectedfriendlyapp-editor-role
rules:
- apiGroups:
  - tools.opdev.io
  resources:
  - disconnectedfriendlyapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tools.opdev.io
  resources:
  - disconnectedfriendlyapps/status
  verbs:
  - get
