# Use the 'create api' subcommand to add watches to this file.
- group: demo.example.com
  version: v1alpha1
  kind: Nginx
  chart: helm-charts/nginx
  overrideValues:
    image.nginx: ${RELATED_IMAGE_NGINX}
#+kubebuilder:scaffold:watch
